name: CI-Test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: 
    runs-on: macos-latest 
    steps: 
    - name: Checkout the code
      uses: actions/checkout@v2
    
    # Build for iPhone
    - name: Build and test ( tvOS 15.0)
      run: xcodebuild test -scheme Backtrace-tvOS -destination 'platform=tvOS Simulator,OS=15.0,name=Apple TV 4K (2nd generation)'

    # test for iPhone
    - name: Build and test ( iOS 15.0)
      run: xcodebuild test -scheme Backtrace-iOS -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro'
